<a href="https://colab.research.google.com/github/lucia-zhy/INFO474_Lab1/blob/main/INFO474_demo_Lucia_1009.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Demo

### Loading Data

In [ ]:
import pandas as pd

In [ ]:
! ls

mxmh_survey_results.csv  sample_data

In [ ]:
df_1 = pd.read_csv("mxmh_survey_results.csv")
df_1

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,...,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,...,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,...,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,...,Sometimes,Never,Never,Never,9.0,7.0,3.0,3.0,Improve,I understand.
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,...,Very frequently,Very frequently,Never,Rarely,7.0,2.0,5.0,9.0,Improve,I understand.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,10/30/2022 14:37:28,17.0,Spotify,2.0,Yes,Yes,No,Rock,Yes,Yes,...,Never,Rarely,Very frequently,Never,7.0,6.0,0.0,9.0,Improve,I understand.
732,11/1/2022 22:26:42,18.0,Spotify,1.0,Yes,Yes,No,Pop,Yes,Yes,...,Never,Never,Sometimes,Sometimes,3.0,2.0,2.0,5.0,Improve,I understand.
733,11/3/2022 23:24:38,19.0,Other streaming service,6.0,Yes,No,Yes,Rap,Yes,No,...,Sometimes,Sometimes,Rarely,Rarely,2.0,2.0,2.0,2.0,Improve,I understand.
734,11/4/2022 17:31:47,19.0,Spotify,5.0,Yes,Yes,No,Classical,No,No,...,Never,Never,Never,Sometimes,2.0,3.0,2.0,1.0,Improve,I understand.
735,11/9/2022 1:55:20,29.0,YouTube Music,2.0,Yes,No,No,Hip hop,Yes,Yes,...,Very frequently,Very frequently,Very frequently,Rarely,2.0,2.0,2.0,5.0,Improve,I understand.

In [ ]:
df_1['Primary streaming service']

0                      Spotify
1                      Pandora
2                      Spotify
3                YouTube Music
4                      Spotify
                ...
731                    Spotify
732                    Spotify
733    Other streaming service
734                    Spotify
735              YouTube Music
Name: Primary streaming service, Length: 736, dtype: object

In [ ]:
#!pip install langdetect
from langdetect import detect

Collecting langdetect
  Downloading langdetect-1.0.9.tar.gz (981 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 981.5/981.5 kB 14.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from langdetect) (1.17.0)
Building wheels for collected packages: langdetect
  Building wheel for langdetect (setup.py) ... done
  Created wheel for langdetect: filename=langdetect-1.0.9-py3-none-any.whl size=993223 sha256=c7b581f2ed571a0a33e8d514bca4c4caf74d2a898f7a9343636641237e355907
  Stored in directory: /root/.cache/pip/wheels/c1/67/88/e844b5b022812e15a52e4eaa38a1e709e99f06f6639d7e3ba7
Successfully built langdetect
Installing collected packages: langdetect
Successfully installed langdetect-1.0.9

In [ ]:
df_1.Anxiety.value_counts()

Anxiety
7.0     122
8.0     115
6.0      83
3.0      69
10.0     67
5.0      59
9.0      56
4.0      56
2.0      44
0.0      35
1.0      29
7.5       1
Name: count, dtype: int64

In [ ]:
df_1.Depression.value_counts()

Depression
7.0     96
2.0     93
6.0     88
0.0     84
8.0     77
3.0     59
4.0     58
5.0     56
10.0    45
1.0     40
9.0     38
3.5      2
Name: count, dtype: int64

In [ ]:
df_1.Insomnia.value_counts()

Insomnia
0.0     149
2.0      88
1.0      82
3.0      68
6.0      62
7.0      59
4.0      59
5.0      58
8.0      49
10.0     34
9.0      27
3.5       1
Name: count, dtype: int64

In [ ]:
df_1.OCD.value_counts()

OCD
0.0     248
2.0      96
1.0      95
3.0      64
5.0      54
4.0      48
7.0      34
6.0      33
8.0      28
10.0     20
9.0      14
8.5       1
5.5       1
Name: count, dtype: int64

In [ ]:
df_1['Regularly/Extremely Anxious'] = df_1.Anxiety.apply(lambda x: 'Yes' if (x == 10.0) else 'No')
df_1['Regularly/Extremely Depression'] = df_1.Depression.apply(lambda x: 'Yes' if (x == 10.0) else 'No')
df_1['Regularly/Extremely Insomnia'] = df_1.Insomnia.apply(lambda x: 'Yes' if (x == 10.0) else 'No')
df_1['Regularly/Extremely OCD'] = df_1.OCD.apply(lambda x: 'Yes' if (x == 10.0) else 'No')

In [ ]:
df_1

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,...,Anxiety,Depression,Insomnia,OCD,Music effects,Permissions,Regularly/Extremely Anxious,Regularly/Extremely Depression,Regularly/Extremely Insomnia,Regularly/Extremely OCD
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,...,3.0,0.0,1.0,0.0,NaN,I understand.,No,No,No,No
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,...,7.0,2.0,2.0,1.0,NaN,I understand.,No,No,No,No
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,...,7.0,7.0,10.0,2.0,No effect,I understand.,No,No,Yes,No
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,...,9.0,7.0,3.0,3.0,Improve,I understand.,No,No,No,No
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,...,7.0,2.0,5.0,9.0,Improve,I understand.,No,No,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
731,10/30/2022 14:37:28,17.0,Spotify,2.0,Yes,Yes,No,Rock,Yes,Yes,...,7.0,6.0,0.0,9.0,Improve,I understand.,No,No,No,No
732,11/1/2022 22:26:42,18.0,Spotify,1.0,Yes,Yes,No,Pop,Yes,Yes,...,3.0,2.0,2.0,5.0,Improve,I understand.,No,No,No,No
733,11/3/2022 23:24:38,19.0,Other streaming service,6.0,Yes,No,Yes,Rap,Yes,No,...,2.0,2.0,2.0,2.0,Improve,I understand.,No,No,No,No
734,11/4/2022 17:31:47,19.0,Spotify,5.0,Yes,Yes,No,Classical,No,No,...,2.0,3.0,2.0,1.0,Improve,I understand.,No,No,No,No
735,11/9/2022 1:55:20,29.0,YouTube Music,2.0,Yes,No,No,Hip hop,Yes,Yes,...,2.0,2.0,2.0,5.0,Improve,I understand.,No,No,No,No

In [ ]:
df_1['Regularly/Extremely Anxious'].value_counts()

Regularly/Extremely Anxious
No     669
Yes     67
Name: count, dtype: int64

In [ ]:
df_1['Regularly/Extremely Depression'].value_counts()

Regularly/Extremely Depression
No     691
Yes     45
Name: count, dtype: int64

In [ ]:
df_1['Regularly/Extremely Insomnia'].value_counts()

Regularly/Extremely Insomnia
No     702
Yes     34
Name: count, dtype: int64

In [ ]:
df_1['Regularly/Extremely OCD'].value_counts()

Regularly/Extremely OCD
No     716
Yes     20
Name: count, dtype: int64

In [ ]:
df_1.to_csv('updated_music_health_survey_results.csv')